POST http://localhost:3001/login
Content-Type: application/json

    { "username": "admin",
 "password": "admin"}



###


GET http://localhost:3001/super-secure-resource
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NTY5Mjc0ODksImV4cCI6MTY1NjkyODc4OX0.TKuxVgInCV0drqADmGEpz6OJOhDvz6Et7WLlKKb69Og



