POST http://localhost:3001/login
Content-Type: application/json

    { "username": "admin",
 "password": "admin"}



###


GET http://localhost:3001/super-secure-resource
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4iLCJpYXQiOjE2NTY5NDAwOTUsImV4cCI6MTY1Njk0MDExMH0.o9wzUNqaspthrcnhKL9nU5WIZM8zVbgRxOFWe_50Ns0



